### ISSUE TITLE
No recent version bumps in 30 days

### ISSUE THREAD

**Issue by hunmar** [hotio/prowlarr#5]
I hope you're doing well. I wanted to take a moment to thank you for maintaining the custom Docker builds. Your work is incredibly valuable to the community, and it's much appreciated!

I’m currently using your Docker build for Prowlarr, and I noticed that a new version has been released. Could you please bump the version for the Docker Prowlarr image whenever you have a chance? It would be really helpful.

Thanks again for all your hard work and dedication!

**Comment by hunmar** [comment]
Thanks!

**Comment by mrhotio** [comment]
There’s an issue with their api iirc
